### ISSUE TITLE
Raise the length of a URL in the models

### ISSUE THREAD

**Issue by mkoistinen** [discovery/django-bitly#6]
A good read on the subject: http://www.boutell.com/newfaq/misc/urllength.html

Obviously, long URLs are dumb, but, sometimes we have to have them, and when we do, we often use URL-shorteners to make them friendlier.  Ergo, django-bitly should probably handle longer URLs =)

The article above mentions a practical limit of 2048 or so.  This seems a bit much, but 200 (current) seems unreasonably low.  Maybe 512 or 1024?

**Comment by fcurella** [comment]
fixed via #13
